// <auto-generated />
using System;
using System.Text.Json;
using IglesiaBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IglesiaBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IglesiaBackend.Features.ChurchFunctionRoles.ChurchFunctionRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorityLevel")
                        .HasColumnType("integer")
                        .HasColumnName("authority_level");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int?>("IdUserCreateAt")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_create_at");

                    b.Property<int?>("IdUserDeletedAt")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_deleted_at");

                    b.Property<int?>("IdUserUpdateAt")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_update_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_at");

                    b.HasKey("Id")
                        .HasName("pk_church_function_roles");

                    b.ToTable("church_function_roles", (string)null);
                });

            modelBuilder.Entity("IglesiaBackend.Features.EventRecordTypes.EventRecordType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("EventId")
                        .HasColumnType("integer")
                        .HasColumnName("event_id");

                    b.Property<int?>("IdUserCreateAt")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_create_at");

                    b.Property<int?>("IdUserDeletedAt")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_deleted_at");

                    b.Property<int?>("IdUserUpdateAt")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_update_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("RecordTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("record_type_id");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_at");

                    b.HasKey("Id")
                        .HasName("pk_event_record_types");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_event_record_types_event_id");

                    b.HasIndex("RecordTypeId")
                        .HasDatabaseName("ix_event_record_types_record_type_id");

                    b.ToTable("event_record_types", (string)null);
                });

            modelBuilder.Entity("IglesiaBackend.Features.Events.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowMultipleSubmissionsPerDay")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_multiple_submissions_per_day");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("end_date");

                    b.Property<string>("EndType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("end_type");

                    b.Property<int?>("IdUserCreateAt")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_create_at");

                    b.Property<int?>("IdUserDeletedAt")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_deleted_at");

                    b.Property<int?>("IdUserUpdateAt")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_update_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsInPerson")
                        .HasColumnType("boolean")
                        .HasColumnName("is_in_person");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("boolean")
                        .HasColumnName("is_recurring");

                    b.Property<int?>("MaxOccurrences")
                        .HasColumnType("integer")
                        .HasColumnName("max_occurrences");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<int?>("OrganizationStructureId")
                        .HasColumnType("integer")
                        .HasColumnName("organization_structure_id");

                    b.Property<int>("RecurrenceInterval")
                        .HasColumnType("integer")
                        .HasColumnName("recurrence_interval");

                    b.Property<string>("RecurrenceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("recurrence_type");

                    b.Property<string>("RecurringDays")
                        .HasColumnType("text")
                        .HasColumnName("recurring_days");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_at");

                    b.HasKey("Id")
                        .HasName("pk_events");

                    b.HasIndex("OrganizationStructureId")
                        .HasDatabaseName("ix_events_organization_structure_id");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("IglesiaBackend.Features.Members.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("address");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("birth_date");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Document")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("document");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<JsonDocument>("ExtraData")
                        .HasColumnType("jsonb")
                        .HasColumnName("extra_data");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("first_name");

                    b.Property<int?>("IdUserCreateAt")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_create_at");

                    b.Property<int?>("IdUserDeletedAt")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_deleted_at");

                    b.Property<int?>("IdUserUpdateAt")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_update_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("last_name");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_at");

                    b.HasKey("Id")
                        .HasName("pk_members");

                    b.ToTable("members", (string)null);
                });

            modelBuilder.Entity("IglesiaBackend.Features.OrganizationMembers.OrganizationMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("assigned_at");

                    b.Property<int>("ChurchFunctionRoleId")
                        .HasColumnType("integer")
                        .HasColumnName("church_function_role_id");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("finished_at");

                    b.Property<int?>("IdUserCreateAt")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_create_at");

                    b.Property<int?>("IdUserDeletedAt")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_deleted_at");

                    b.Property<int?>("IdUserUpdateAt")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_update_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("MemberId")
                        .HasColumnType("integer")
                        .HasColumnName("member_id");

                    b.Property<int>("OrganizationStructureId")
                        .HasColumnType("integer")
                        .HasColumnName("organization_structure_id");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_at");

                    b.HasKey("Id")
                        .HasName("pk_organization_members");

                    b.HasIndex("ChurchFunctionRoleId")
                        .HasDatabaseName("ix_organization_members_church_function_role_id");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("ix_organization_members_member_id");

                    b.HasIndex("OrganizationStructureId")
                        .HasDatabaseName("ix_organization_members_organization_structure_id");

                    b.ToTable("organization_members", (string)null);
                });

            modelBuilder.Entity("IglesiaBackend.Features.OrganizationStructures.OrganizationStructure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int?>("IdUserCreateAt")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_create_at");

                    b.Property<int?>("IdUserDeletedAt")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_deleted_at");

                    b.Property<int?>("IdUserUpdateAt")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_update_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<int>("OrganizationTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("organization_type_id");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_id");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_at");

                    b.HasKey("Id")
                        .HasName("pk_organization_structures");

                    b.HasIndex("OrganizationTypeId")
                        .HasDatabaseName("ix_organization_structures_organization_type_id");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_organization_structures_parent_id");

                    b.ToTable("organization_structures", (string)null);
                });

            modelBuilder.Entity("IglesiaBackend.Features.OrganizationTypes.OrganizationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int?>("IdUserCreateAt")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_create_at");

                    b.Property<int?>("IdUserDeletedAt")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_deleted_at");

                    b.Property<int?>("IdUserUpdateAt")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_update_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_at");

                    b.HasKey("Id")
                        .HasName("pk_organization_types");

                    b.ToTable("organization_types", (string)null);
                });

            modelBuilder.Entity("IglesiaBackend.Features.RecordTypeFields.RecordTypeField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_at");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("data_type");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("FieldOrder")
                        .HasColumnType("integer")
                        .HasColumnName("field_order");

                    b.Property<int?>("IdUserCreateAt")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_create_at");

                    b.Property<int?>("IdUserDeletedAt")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_deleted_at");

                    b.Property<int?>("IdUserUpdateAt")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_update_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<string>("MemberSelectionLogic")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("member_selection_logic");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("RecordTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("record_type_id");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_at");

                    b.HasKey("Id")
                        .HasName("pk_record_type_fields");

                    b.HasIndex("RecordTypeId")
                        .HasDatabaseName("ix_record_type_fields_record_type_id");

                    b.ToTable("record_type_fields", (string)null);
                });

            modelBuilder.Entity("IglesiaBackend.Features.RecordTypes.RecordType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("description");

                    b.Property<int?>("IdUserCreateAt")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_create_at");

                    b.Property<int?>("IdUserDeletedAt")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_deleted_at");

                    b.Property<int?>("IdUserUpdateAt")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_update_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int?>("TargetFunctionRoleId")
                        .HasColumnType("integer")
                        .HasColumnName("target_function_role_id");

                    b.Property<int?>("TargetOrganizationTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("target_organization_type_id");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_at");

                    b.HasKey("Id")
                        .HasName("pk_record_types");

                    b.HasIndex("TargetFunctionRoleId")
                        .HasDatabaseName("ix_record_types_target_function_role_id");

                    b.HasIndex("TargetOrganizationTypeId")
                        .HasDatabaseName("ix_record_types_target_organization_type_id");

                    b.ToTable("record_types", (string)null);
                });

            modelBuilder.Entity("IglesiaBackend.Features.RegistryEvents.RegistryEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_at");

                    b.Property<JsonDocument>("DataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("data_json");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("EventId")
                        .HasColumnType("integer")
                        .HasColumnName("event_id");

                    b.Property<int?>("IdUserCreateAt")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_create_at");

                    b.Property<int?>("IdUserDeletedAt")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_deleted_at");

                    b.Property<int?>("IdUserUpdateAt")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_update_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("LeaderId")
                        .HasColumnType("integer")
                        .HasColumnName("leader_id");

                    b.Property<int>("RecordTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("record_type_id");

                    b.Property<DateTime>("RegistryDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("registry_date");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_at");

                    b.HasKey("Id")
                        .HasName("pk_registry_events");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_registry_events_event_id");

                    b.HasIndex("LeaderId")
                        .HasDatabaseName("ix_registry_events_leader_id");

                    b.HasIndex("RecordTypeId")
                        .HasDatabaseName("ix_registry_events_record_type_id");

                    b.ToTable("registry_events", (string)null);
                });

            modelBuilder.Entity("IglesiaBackend.Features.Reports.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Configuration")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("configuration");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<int?>("IdUserCreateAt")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_create_at");

                    b.Property<int?>("IdUserDeletedAt")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_deleted_at");

                    b.Property<int?>("IdUserUpdateAt")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_update_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("TypeReport")
                        .HasColumnType("integer")
                        .HasColumnName("type_report");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_at");

                    b.HasKey("Id")
                        .HasName("pk_reports");

                    b.ToTable("reports", (string)null);
                });

            modelBuilder.Entity("IglesiaBackend.Features.SystemRoles.SystemRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("description");

                    b.Property<int?>("IdUserCreateAt")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_create_at");

                    b.Property<int?>("IdUserDeletedAt")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_deleted_at");

                    b.Property<int?>("IdUserUpdateAt")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_update_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_at");

                    b.HasKey("Id")
                        .HasName("pk_system_roles");

                    b.ToTable("system_roles", (string)null);
                });

            modelBuilder.Entity("IglesiaBackend.Features.UserSystemRoles.UserSystemRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("IdUserCreateAt")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_create_at");

                    b.Property<int?>("IdUserDeletedAt")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_deleted_at");

                    b.Property<int?>("IdUserUpdateAt")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_update_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("SystemRoleId")
                        .HasColumnType("integer")
                        .HasColumnName("system_role_id");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_system_roles");

                    b.HasIndex("SystemRoleId")
                        .HasDatabaseName("ix_user_system_roles_system_role_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_system_roles_user_id");

                    b.ToTable("user_system_roles", (string)null);
                });

            modelBuilder.Entity("IglesiaBackend.Features.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("IdUserCreateAt")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_create_at");

                    b.Property<int?>("IdUserDeletedAt")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_deleted_at");

                    b.Property<int?>("IdUserUpdateAt")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_update_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("MemberId")
                        .HasColumnType("integer")
                        .HasColumnName("member_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("MemberId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_member_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("IglesiaBackend.Features.EventRecordTypes.EventRecordType", b =>
                {
                    b.HasOne("IglesiaBackend.Features.Events.Event", "Event")
                        .WithMany("EventRecordTypes")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_event_record_types_events_event_id");

                    b.HasOne("IglesiaBackend.Features.RecordTypes.RecordType", "RecordType")
                        .WithMany("EventRecordTypes")
                        .HasForeignKey("RecordTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_event_record_types_record_types_record_type_id");

                    b.Navigation("Event");

                    b.Navigation("RecordType");
                });

            modelBuilder.Entity("IglesiaBackend.Features.Events.Event", b =>
                {
                    b.HasOne("IglesiaBackend.Features.OrganizationStructures.OrganizationStructure", "OrganizationStructure")
                        .WithMany("Events")
                        .HasForeignKey("OrganizationStructureId")
                        .HasConstraintName("fk_events_organization_structures_organization_structure_id");

                    b.Navigation("OrganizationStructure");
                });

            modelBuilder.Entity("IglesiaBackend.Features.OrganizationMembers.OrganizationMember", b =>
                {
                    b.HasOne("IglesiaBackend.Features.ChurchFunctionRoles.ChurchFunctionRole", "ChurchFunctionRole")
                        .WithMany()
                        .HasForeignKey("ChurchFunctionRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_organization_members_church_function_roles_church_function_");

                    b.HasOne("IglesiaBackend.Features.Members.Member", "Member")
                        .WithMany("OrganizationMemberships")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_organization_members_members_member_id");

                    b.HasOne("IglesiaBackend.Features.OrganizationStructures.OrganizationStructure", "OrganizationStructure")
                        .WithMany("Members")
                        .HasForeignKey("OrganizationStructureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_organization_members_organization_structures_organization_s");

                    b.Navigation("ChurchFunctionRole");

                    b.Navigation("Member");

                    b.Navigation("OrganizationStructure");
                });

            modelBuilder.Entity("IglesiaBackend.Features.OrganizationStructures.OrganizationStructure", b =>
                {
                    b.HasOne("IglesiaBackend.Features.OrganizationTypes.OrganizationType", "OrganizationType")
                        .WithMany()
                        .HasForeignKey("OrganizationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_organization_structures_organization_types_organization_typ");

                    b.HasOne("IglesiaBackend.Features.OrganizationStructures.OrganizationStructure", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_organization_structures_organization_structures_parent_id");

                    b.Navigation("OrganizationType");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("IglesiaBackend.Features.RecordTypeFields.RecordTypeField", b =>
                {
                    b.HasOne("IglesiaBackend.Features.RecordTypes.RecordType", "RecordType")
                        .WithMany("Fields")
                        .HasForeignKey("RecordTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_record_type_fields_record_types_record_type_id");

                    b.Navigation("RecordType");
                });

            modelBuilder.Entity("IglesiaBackend.Features.RecordTypes.RecordType", b =>
                {
                    b.HasOne("IglesiaBackend.Features.ChurchFunctionRoles.ChurchFunctionRole", "TargetFunctionRole")
                        .WithMany()
                        .HasForeignKey("TargetFunctionRoleId")
                        .HasConstraintName("fk_record_types_church_function_roles_target_function_role_id");

                    b.HasOne("IglesiaBackend.Features.OrganizationTypes.OrganizationType", "TargetOrganizationType")
                        .WithMany()
                        .HasForeignKey("TargetOrganizationTypeId")
                        .HasConstraintName("fk_record_types_organization_types_target_organization_type_id");

                    b.Navigation("TargetFunctionRole");

                    b.Navigation("TargetOrganizationType");
                });

            modelBuilder.Entity("IglesiaBackend.Features.RegistryEvents.RegistryEvent", b =>
                {
                    b.HasOne("IglesiaBackend.Features.Events.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_registry_events_events_event_id");

                    b.HasOne("IglesiaBackend.Features.Members.Member", "Leader")
                        .WithMany()
                        .HasForeignKey("LeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_registry_events_members_leader_id");

                    b.HasOne("IglesiaBackend.Features.RecordTypes.RecordType", "RecordType")
                        .WithMany()
                        .HasForeignKey("RecordTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_registry_events_record_types_record_type_id");

                    b.Navigation("Event");

                    b.Navigation("Leader");

                    b.Navigation("RecordType");
                });

            modelBuilder.Entity("IglesiaBackend.Features.UserSystemRoles.UserSystemRole", b =>
                {
                    b.HasOne("IglesiaBackend.Features.SystemRoles.SystemRole", "SystemRole")
                        .WithMany("UserSystemRoles")
                        .HasForeignKey("SystemRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_system_roles_system_roles_system_role_id");

                    b.HasOne("IglesiaBackend.Features.Users.User", "User")
                        .WithMany("UserSystemRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_system_roles_users_user_id");

                    b.Navigation("SystemRole");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IglesiaBackend.Features.Users.User", b =>
                {
                    b.HasOne("IglesiaBackend.Features.Members.Member", "Member")
                        .WithOne("User")
                        .HasForeignKey("IglesiaBackend.Features.Users.User", "MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_members_member_id");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("IglesiaBackend.Features.Events.Event", b =>
                {
                    b.Navigation("EventRecordTypes");
                });

            modelBuilder.Entity("IglesiaBackend.Features.Members.Member", b =>
                {
                    b.Navigation("OrganizationMemberships");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IglesiaBackend.Features.OrganizationStructures.OrganizationStructure", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Events");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("IglesiaBackend.Features.RecordTypes.RecordType", b =>
                {
                    b.Navigation("EventRecordTypes");

                    b.Navigation("Fields");
                });

            modelBuilder.Entity("IglesiaBackend.Features.SystemRoles.SystemRole", b =>
                {
                    b.Navigation("UserSystemRoles");
                });

            modelBuilder.Entity("IglesiaBackend.Features.Users.User", b =>
                {
                    b.Navigation("UserSystemRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
